---

- name: My Debug
# hostname can be passed as argument to playbook, otherwise use the default inventory hosts under 'tempest_hosts'
  hosts: local
  gather_facts: False
  vars:
  - my_var: " "
    debug:
      msg: >
        my_var = {{ my_var }}
  post_tasks:
    - name: Checking var
      debug: msg=OK
      when: my_var | trim  == ''
      tags:
      - always

