---

- name: Include Controller tasks
  include_tasks: controller.yml
  when: inventory_hostname in groups['controller']

- name: Include Compute tasks
  include_tasks: compute.yml
  when: inventory_hostname in groups['computeovsdpdk'] | default([]) | union(groups['compute'] | default([]))
