---

- name: Snapshot the Undercloud (clean state, before tempest setup)
  shell: |
    domain_name={{ vars['domain_name'] }}
    virsh snapshot-list $domain_name --name | grep $domain_name || virsh snapshot-create-as $domain_name ${domain_name}_clean
  register: out
  when: create_snapshot
