---
- name: port number should be set in vars defaults
  vars:
    sudo_user: "{{ lookup('env','USER') }}"
    pubkey_path: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"
  debug:
    msg: >
      Host Port = 222,
      sudo_user (environment variable) = {{ sudo_user }},
      pubkey_path (environment variable) = {{ pubkey_path }}

# copy RSA public key to host
#- name: make direcotry
#  file:
#    path: "/home/{{sudo_user}}/.ssh"
#    state: directory
#
#- name: create empty file
#  file:
#    path: "/home/{{sudo_user}}/.ssh/authorized_keys"
#    state: touch
#
#- name: put pubkey
#  lineinfile:
#    path: "/home/{{sudo_user}}/.ssh/authorized_keys"
#    line: "{{ pubkey_path }}"
#  register: out
#
#- debug: var=out.stdout_lines


- name: Create SSH Tunnel from Host (port 222) to Undercloud
  shell: |
    #yum install -y iptables-services
    #systemctl enable iptables.service
    #systemctl start iptables.service
    ipv4_undercloud=`virsh net-dhcp-leases management| grep undercloud| awk '{print $5}'| grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" `
    echo ipv4_undercloud = $ipv4_undercloud
    iptables -I OUTPUT  -d 0.0.0.0/0 -j ACCEPT -v
    iptables -I FORWARD  -d 0.0.0.0/0 -j ACCEPT -v
    iptables -I INPUT  -d 0.0.0.0/0 -j ACCEPT -v
    iptables -t nat -I PREROUTING -d 0.0.0.0/0 -p tcp --dport 222 -j DNAT --to-destination $ipv4_undercloud:22 -v
    #modprobe ip_tables
    iptables-save > /etc/sysconfig/iptables
  register: out
#  failed_when: "out.stderr"


