---

- name: Copy SSH Key from localhost to Remote Virt Host (bare-metal)
# hostname can be passed as argument to playbook, otherwise use the default inventory hosts under 'tempest_hosts'
  hosts: local
  vars:
    filter: "{{ hostname | default('.*') }}"
  gather_facts: false
  tasks:
  - include_role: name=ssh/ssh_send_rsa_key
    with_items: "{{ groups['tempest_hosts'] | select('search',filter) | list }}"
    loop_control:
      loop_var: server
  post_tasks:
  - include_role: name=pre_post_tasks/check_output_error

- name: Configure Host Firewall with ssh tunnel on port 222
# hostname can be passed as argument to playbook, otherwise use the default inventory hosts under 'tempest_hosts'
  hosts: "{{ hostname | default('tempest_hosts') }}"
  vars:
#    filter: "{{ hostname | default('.*') }}"
  gather_facts: false
  tasks:
  - include_role: name=ssh/ssh_tunnel
#    with_items: "{{ groups['tempest_hosts'] | select('search',filter) | list }}"
#    loop_control:
#      loop_var: server
  post_tasks:
  - include_role: name=pre_post_tasks/check_output_error

- name: Snapshot the Undercloud (clean state, before tempest setup)
  hosts: "{{ hostname | default('tempest_hosts') }}"
  vars:
    create_snapshot: True
    domain_name: undercloud-0
#    filter: "{{ hostname | default('.*') }}"
  gather_facts: false
  tasks:
  - include_role: name=virsh
#    with_items: "{{ groups['tempest_hosts'] | select('search',filter) | list }}"
#    loop_control:
#      loop_var: server
  post_tasks:
  - include_role: name=pre_post_tasks/check_output_error

- name: Copy SSH Key from localhost to Tempest Undercloud via tunnel port 222
# hostname can be passed as argument to playbook, otherwise use the default inventory hosts under 'tempest_hosts'
#  tags:
#  - tempest_debug
  hosts: local
  vars:
    ssh_user: stack
    ssh_port: 222
    filter: "{{ hostname | default('.*') }}"
  gather_facts: false
  tasks:
  - include_role: name=ssh/ssh_send_rsa_key
    with_items: "{{ groups['tempest_hosts'] | select('search',filter) | list }}"
    loop_control:
      loop_var: server
  post_tasks:
  - include_role: name=pre_post_tasks/check_output_error

- name: Tempest deployment on Undercloud Virtual Env
# target host is usually the undercloud-0 VM inside the baremetal host (e.g. puma)
  hosts: "{{ hostname | default('tempest_hosts') }}"
  vars:
    ansible_user: stack
    ansible_port: 222
#    ssh_user: stack
#    ssh_port: 222
#    filter: "{{ hostname | default('.*') }}"
  gather_facts: false
  tasks:
  - include_role: name=remote_tempest
#    with_items: "{{ groups['tempest_hosts'] | select('search',filter) | list }}"
#    loop_control:
#      loop_var: server
  post_tasks:
  - include_role: name=pre_post_tasks/check_output_error
#  - name: Checking if output contains errors
#    fail: msg={{ out.stderr.split('\n') }}
#    when: out is defined and out.stderr is defined and (out.stderr | lower | regex_search('error|fail|not found|stacktrace') or out.rc != 0)
##      failed_when: "out.stderr"
#    tags:
#    - always
