---
- name: Copy SSH Key to Remote server
  shell: |
    PROMPT_COMMAND=
    set -v
    host_name={{ hostvars[server].ansible_host | default('localhost') }}
    host_ip=$(dig +short $host_name)
    host_user={{ ssh_user if ssh_user is defined else hostvars[server].ansible_user | default('root') }}
    host_port={{ ssh_port if ssh_port is defined else hostvars[server].ansible_port | default('22') }}
    key_file={{ hostvars[server].ansible_ssh_private_key_file | default('__')}}
    hosts_file={{ hostvars[server].ssh_hosts_file | default('__')}}

    echo Generating SSH key for both hostname = $host_name, and ip = $host_ip
    echo Where user = $host_user, port = $host_port, key = $key_file, hosts_file = $hosts_file
    ssh-keygen -f $hosts_file -R [$host_name]:$host_port
    ssh-keygen -f $hosts_file -R [$host_ip]:$host_port
    ssh -o StrictHostKeyChecking=no $host_user@$host_name -p $host_port
    #ssh-copy-id $host_user@$host_name -p $host_port
    ssh-add -l |grep -q `ssh-keygen -lf $key_file  | awk '{print $2}'` || ssh-add $key_file && ssh-copy-id $host_user@$host_name -p $host_port
    set +v
  register: out
  failed_when: out.stderr is defined and (out.stderr | lower | regex_search('error|fail') or out.rc != 0)


